// src/pages/SourcesPage/components/MotcleFlux/mockData.js

export const mockArticles = [
  {
    id: 1,
    title: "Football : La Coupe du Monde 2026 préparations intensives",
    description: "Les équipes se préparent activement pour la prochaine Coupe du Monde de football qui aura lieu en 2026. Les infrastructures sont en cours de finalisation dans les trois pays hôtes...",
    source: "L'Équipe",
    sourceUrl: "https://lequipe.fr",
    sourceFavicon: "https://images.unsplash.com/photo-1529900748604-07564a03e7a6?w=32&h=32&fit=crop&crop=faces",
    url: "https://lequipe.fr/football/article1",
    publishedAt: new Date(Date.now() - 2 * 3600000), // 2h ago
    keywords: ["football", "coupe du monde", "2026"],
    category: "Sport",
    contentType: "article",
    readTime: "3 min",
    isRead: false,
    isFavorite: false,
    isFollowed: false,
    image: "https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=600&h=300&fit=crop",
    matchedKeywords: ["football"],
    engagement: { views: 1245, shares: 34, comments: 12 }
  },
  {
    id: 2,
    title: "Transferts football : Les dernières rumeurs du mercato estival",
    description: "Le mercato estival bat son plein avec de nombreuses rumeurs de transferts dans le monde du football européen. Les clubs cherchent à renforcer leurs effectifs...",
    source: "France Football",
    sourceUrl: "https://francefootball.fr",
    sourceFavicon: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=32&h=32&fit=crop&crop=faces",
    url: "https://francefootball.fr/transferts",
    publishedAt: new Date(Date.now() - 4 * 3600000), // 4h ago
    keywords: ["football", "transferts", "mercato"],
    category: "Sport",
    contentType: "video",
    duration: "12:45",
    isRead: true,
    isFavorite: true,
    isFollowed: true,
    image: "https://images.unsplash.com/photo-1522778119026-d647f0596c20?w=600&h=300&fit=crop",
    matchedKeywords: ["football"],
    engagement: { views: 2341, shares: 89, comments: 23 }
  },
  {
    id: 3,
    title: "Football féminin : Record d'audience pour la finale du championnat",
    description: "La finale du championnat de football féminin a battu tous les records d'audience télévisée, marquant une étape importante pour le sport féminin en France...",
    source: "RMC Sport",
    sourceUrl: "https://rmcsport.bfmtv.com",
    sourceFavicon: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=32&h=32&fit=crop&crop=faces",
    url: "https://rmcsport.bfmtv.com/football-feminin",
    publishedAt: new Date(Date.now() - 6 * 3600000), // 6h ago
    keywords: ["football", "féminin", "audience"],
    category: "Sport",
    contentType: "audio",
    duration: "35:20",
    isRead: false,
    isFavorite: false,
    isFollowed: false,
    image: "https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=600&h=300&fit=crop",
    matchedKeywords: ["football"],
    engagement: { views: 892, shares: 45, comments: 8 }
  },
  {
    id: 4,
    title: "Intelligence artificielle dans le football : La révolution tactique",
    description: "L'IA transforme l'analyse tactique dans le football professionnel avec des outils de plus en plus sophistiqués. Les entraîneurs utilisent désormais des algorithmes avancés...",
    source: "TechCrunch",
    sourceUrl: "https://techcrunch.com",
    sourceFavicon: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=32&h=32&fit=crop&crop=faces",
    url: "https://techcrunch.com/ai-football",
    publishedAt: new Date(Date.now() - 12 * 3600000), // 12h ago
    keywords: ["football", "intelligence artificielle", "tactique"],
    category: "Tech",
    contentType: "document",
    fileSize: "2.4 MB",
    isRead: false,
    isFavorite: false,
    isFollowed: false,
    image: "https://images.unsplash.com/photo-1593104547489-5cfb3839a3b5?w=600&h=300&fit=crop",
    matchedKeywords: ["football"],
    engagement: { views: 3456, shares: 156, comments: 67 }
  },
  {
    id: 5,
    title: "Technologie blockchain : Révolution dans la finance digitale",
    description: "La blockchain transforme le secteur financier avec de nouvelles applications décentralisées. Les banques adoptent progressivement cette technologie révolutionnaire...",
    source: "Les Échos",
    sourceUrl: "https://lesechos.fr",
    sourceFavicon: "https://images.unsplash.com/photo-1556157382-97eda2f9e2bf?w=32&h=32&fit=crop&crop=faces",
    url: "https://lesechos.fr/blockchain-finance",
    publishedAt: new Date(Date.now() - 8 * 3600000), // 8h ago
    keywords: ["technologie", "blockchain", "finance"],
    category: "Tech",
    contentType: "post",
    platform: "LinkedIn",
    isRead: false,
    isFavorite: false,
    isFollowed: false,
    image: "https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=600&h=300&fit=crop",
    matchedKeywords: ["technologie"],
    engagement: { views: 2156, shares: 78, comments: 45 }
  },
  {
    id: 6,
    title: "Changement climatique : Nouveaux records de température en Europe",
    description: "L'Europe fait face à des températures record cet été, confirmant les tendances du réchauffement climatique. Les scientifiques tirent la sonnette d'alarme...",
    source: "Le Monde",
    sourceUrl: "https://lemonde.fr",
    sourceFavicon: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=32&h=32&fit=crop&crop=faces",
    url: "https://lemonde.fr/climat-record",
    publishedAt: new Date(Date.now() - 10 * 3600000), // 10h ago
    keywords: ["climat", "température", "Europe"],
    category: "News",
    contentType: "image",
    resolution: "1920x1080",
    isRead: false,
    isFavorite: true,
    isFollowed: false,
    image: "https://images.unsplash.com/photo-1569163139394-de44cb8fb407?w=600&h=300&fit=crop",
    matchedKeywords: ["climat"],
    engagement: { views: 1876, shares: 92, comments: 34 }
  },
  {
    id: 7,
    title: "Économie française : Nouveau rapport sur l'inflation",
    description: "L'INSEE publie son rapport trimestriel sur l'inflation en France. Les chiffres révèlent une stabilisation des prix dans plusieurs secteurs clés...",
    source: "INSEE",
    sourceUrl: "https://insee.fr",
    sourceFavicon: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=32&h=32&fit=crop&crop=faces",
    url: "https://insee.fr/rapport-inflation-q3",
    publishedAt: new Date(Date.now() - 14 * 3600000), // 14h ago
    keywords: ["économie", "inflation", "INSEE"],
    category: "Business",
    contentType: "link",
    domain: "insee.fr",
    isRead: false,
    isFavorite: false,
    isFollowed: true,
    image: "https://images.unsplash.com/photo-1560472354-b33ff0c44a43?w=600&h=300&fit=crop",
    matchedKeywords: ["économie"],
    engagement: { views: 1432, shares: 67, comments: 19 }
  }
];