export const mockNewsletters = [
  {
    id: '1',
    name: 'Morning Brew',
    publisher: 'Morning Brew Media',
    description: 'Business news and insights that makes you smarter in just 5 minutes. Get the latest from Wall Street, Silicon Valley, and everywhere in between.',
    logo: 'https://images.unsplash.com/photo-1611224923853-80b023f02d71?w=100&h=100&fit=crop&crop=center',
    categories: ['business', 'finance', 'news'],
    frequency: 'daily',
    subscriberCount: 2500000,
    rating: 4.8,
    isSubscribed: true,
    status: 'active',
    unreadCount: 3,
    lastIssueDate: '2025-06-24',
    websiteUrl: 'https://morningbrew.com',
    sampleUrl: 'https://morningbrew.com/sample',
    weeklyGrowth: 15,
    createdAt: '2023-01-15',
    language: 'en',
    isFavorite: true
  },
  {
    id: '2',
    name: 'The Hustle',
    publisher: 'HubSpot',
    description: 'Tech and business news that doesn\'t suck. Join 2M+ readers who stay ahead of the curve with our daily newsletter.',
    logo: 'https://images.unsplash.com/photo-1560472354-b33ff0c44a43?w=100&h=100&fit=crop&crop=center',
    categories: ['tech', 'business', 'startup'],
    frequency: 'daily',
    subscriberCount: 2000000,
    rating: 4.7,
    isSubscribed: false,
    status: null,
    unreadCount: 0,
    lastIssueDate: '2025-06-24',
    websiteUrl: 'https://thehustle.co',
    sampleUrl: 'https://thehustle.co/sample',
    weeklyGrowth: 12,
    createdAt: '2023-02-20',
    language: 'en',
    isFavorite: false
  },
  {
    id: '3',
    name: 'Dense Discovery',
    publisher: 'Kai Brach',
    description: 'A weekly newsletter at the intersection of design, technology and sustainability. Curated with ❤️ for designers and creative professionals.',
    logo: 'https://images.unsplash.com/photo-1558655146-364adaf25b72?w=100&h=100&fit=crop&crop=center',
    categories: ['design', 'tech', 'productivity'],
    frequency: 'weekly',
    subscriberCount: 65000,
    rating: 4.9,
    isSubscribed: true,
    status: 'active',
    unreadCount: 1,
    lastIssueDate: '2025-06-22',
    websiteUrl: 'https://densediscovery.com',
    sampleUrl: 'https://densediscovery.com/sample',
    weeklyGrowth: 8,
    createdAt: '2023-03-10',
    language: 'en',
    isFavorite: false
  },
  {
    id: '4',
    name: 'Stratechery',
    publisher: 'Ben Thompson',
    description: 'Analysis of the strategy and business side of technology and media, and the impact of technology on society.',
    logo: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=100&h=100&fit=crop&crop=center',
    categories: ['tech', 'business', 'marketing'],
    frequency: 'weekly',
    subscriberCount: 150000,
    rating: 4.6,
    isSubscribed: false,
    status: null,
    unreadCount: 0,
    lastIssueDate: '2025-06-20',
    websiteUrl: 'https://stratechery.com',
    sampleUrl: 'https://stratechery.com/sample',
    weeklyGrowth: 5,
    createdAt: '2023-01-08',
    language: 'en',
    isFavorite: false
  },
  {
    id: '5',
    name: 'TLDR',
    publisher: 'TLDR Media',
    description: 'Byte-sized news for busy techies. Get the latest tech news in 5 minutes. Covering AI, crypto, startups, and more.',
    logo: 'https://images.unsplash.com/photo-1518709268805-4e9042af2176?w=100&h=100&fit=crop&crop=center',
    categories: ['tech', 'startup'],
    frequency: 'daily',
    subscriberCount: 800000,
    rating: 4.5,
    isSubscribed: true,
    status: 'paused',
    unreadCount: 0,
    lastIssueDate: '2025-06-24',
    websiteUrl: 'https://tldr.tech',
    sampleUrl: 'https://tldr.tech/sample',
    weeklyGrowth: 20,
    createdAt: '2023-04-15',
    language: 'en',
    isFavorite: false
  },
  {
    id: '6',
    name: 'The Skimm',
    publisher: 'theSkimm',
    description: 'We make it easier to be smarter. Daily newsletter breaking down what you need to know to start your day.',
    logo: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?w=100&h=100&fit=crop&crop=center',
    categories: ['news', 'lifestyle'],
    frequency: 'daily',
    subscriberCount: 7000000,
    rating: 4.4,
    isSubscribed: false,
    status: null,
    unreadCount: 0,
    lastIssueDate: '2025-06-24',
    websiteUrl: 'https://theskimm.com',
    sampleUrl: 'https://theskimm.com/sample',
    weeklyGrowth: 10,
    createdAt: '2023-01-01',
    language: 'en',
    isFavorite: false
  },
  {
    id: '7',
    name: 'Product Hunt Daily',
    publisher: 'Product Hunt',
    description: 'The best new products, every day. Discover amazing products built by makers around the world.',
    logo: 'https://images.unsplash.com/photo-1472851294608-062f824d29cc?w=100&h=100&fit=crop&crop=center',
    categories: ['tech', 'startup', 'productivity'],
    frequency: 'daily',
    subscriberCount: 500000,
    rating: 4.3,
    isSubscribed: false,
    status: null,
    unreadCount: 0,
    lastIssueDate: '2025-06-24',
    websiteUrl: 'https://producthunt.com',
    sampleUrl: 'https://producthunt.com/sample',
    weeklyGrowth: 18,
    createdAt: '2023-05-20',
    language: 'en',
    isFavorite: false
  },
  {
    id: '8',
    name: 'Wellness Wednesday',
    publisher: 'Health & Wellness Co',
    description: 'Weekly tips and insights for a healthier, more balanced lifestyle. Evidence-based wellness advice.',
    logo: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=100&h=100&fit=crop&crop=center',
    categories: ['health', 'lifestyle'],
    frequency: 'weekly',
    subscriberCount: 120000,
    rating: 4.7,
    isSubscribed: true,
    status: 'active',
    unreadCount: 2,
    lastIssueDate: '2025-06-18',
    websiteUrl: 'https://wellnesswednesday.com',
    sampleUrl: 'https://wellnesswednesday.com/sample',
    weeklyGrowth: 6,
    createdAt: '2023-06-01',
    language: 'en',
    isFavorite: true
  },
  {
    id: '9',
    name: 'La Lettre Tech',
    publisher: 'TechFrance',
    description: 'L\'actualité tech française et internationale. Analyses, tendances et insights pour les professionnels du numérique.',
    logo: 'https://images.unsplash.com/photo-1560472355-536de3962603?w=100&h=100&fit=crop&crop=center',
    categories: ['tech', 'business'],
    frequency: 'biweekly',
    subscriberCount: 45000,
    rating: 4.2,
    isSubscribed: true,
    status: 'active',
    unreadCount: 1,
    lastIssueDate: '2025-06-21',
    websiteUrl: 'https://techfrance.fr',
    sampleUrl: 'https://techfrance.fr/sample',
    weeklyGrowth: 14,
    createdAt: '2023-07-12',
    language: 'fr',
    isFavorite: false
  },
  {
    id: '10',
    name: 'Weekly Science',
    publisher: 'Scientific American',
    description: 'The latest breakthroughs in science and technology. From quantum computing to space exploration.',
    logo: 'https://images.unsplash.com/photo-1532094349884-543bc11b234d?w=100&h=100&fit=crop&crop=center',
    categories: ['science', 'tech'],
    frequency: 'weekly',
    subscriberCount: 280000,
    rating: 4.6,
    isSubscribed: false,
    status: null,
    unreadCount: 0,
    lastIssueDate: '2025-06-23',
    websiteUrl: 'https://scientificamerican.com',
    sampleUrl: 'https://scientificamerican.com/sample',
    weeklyGrowth: 7,
    createdAt: '2023-03-25',
    language: 'en',
    isFavorite: false
  },
  {
    id: '11',
    name: 'Marketing Brew',
    publisher: 'Morning Brew',
    description: 'Marketing news and insights for the modern marketer. Trends, case studies, and industry analysis.',
    logo: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=100&h=100&fit=crop&crop=center',
    categories: ['marketing', 'business'],
    frequency: 'weekly',
    subscriberCount: 350000,
    rating: 4.5,
    isSubscribed: false,
    status: null,
    unreadCount: 0,
    lastIssueDate: '2025-06-23',
    websiteUrl: 'https://marketingbrew.com',
    sampleUrl: 'https://marketingbrew.com/sample',
    weeklyGrowth: 11,
    createdAt: '2023-04-08',
    language: 'en',
    isFavorite: false
  },
  {
    id: '12',
    name: 'Design Systems Weekly',
    publisher: 'Design Systems Coalition',
    description: 'Everything about design systems, component libraries, and design tokens. For designers and developers.',
    logo: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=100&h=100&fit=crop&crop=center',
    categories: ['design', 'tech'],
    frequency: 'weekly',
    subscriberCount: 85000,
    rating: 4.8,
    isSubscribed: true,
    status: 'active',
    unreadCount: 0,
    lastIssueDate: '2025-06-22',
    websiteUrl: 'https://designsystems.com',
    sampleUrl: 'https://designsystems.com/sample',
    weeklyGrowth: 9,
    createdAt: '2023-05-15',
    language: 'en',
    isFavorite: false
  },
  {
    id: '13',
    name: 'Fintech Today',
    publisher: 'Financial Innovation Hub',
    description: 'Daily insights into the fintech world. Banking, payments, crypto, and financial innovation.',
    logo: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=100&h=100&fit=crop&crop=center',
    categories: ['finance', 'tech', 'business'],
    frequency: 'daily',
    subscriberCount: 195000,
    rating: 4.4,
    isSubscribed: false,
    status: null,
    unreadCount: 0,
    lastIssueDate: '2025-06-24',
    websiteUrl: 'https://fintechtoday.com',
    sampleUrl: 'https://fintechtoday.com/sample',
    weeklyGrowth: 16,
    createdAt: '2023-06-20',
    language: 'en',
    isFavorite: false
  },
  {
    id: '14',
    name: 'Health Tech Weekly',
    publisher: 'MedTech Insights',
    description: 'The intersection of healthcare and technology. Digital health, medical devices, and health innovation.',
    logo: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1f?w=100&h=100&fit=crop&crop=center',
    categories: ['health', 'tech'],
    frequency: 'weekly',
    subscriberCount: 72000,
    rating: 4.6,
    isSubscribed: true,
    status: 'active',
    unreadCount: 1,
    lastIssueDate: '2025-06-23',
    websiteUrl: 'https://healthtech.com',
    sampleUrl: 'https://healthtech.com/sample',
    weeklyGrowth: 13,
    createdAt: '2023-08-10',
    language: 'en',
    isFavorite: false
  },
  {
    id: '15',
    name: 'Startup Digest',
    publisher: 'Entrepreneur Media',
    description: 'Weekly roundup of startup news, funding rounds, and entrepreneurship insights. From seed to IPO.',
    logo: 'https://images.unsplash.com/photo-1556155092-490a1ba16284?w=100&h=100&fit=crop&crop=center',
    categories: ['startup', 'business'],
    frequency: 'weekly',
    subscriberCount: 420000,
    rating: 4.3,
    isSubscribed: false,
    status: null,
    unreadCount: 0,
    lastIssueDate: '2025-06-22',
    websiteUrl: 'https://startupdigest.com',
    sampleUrl: 'https://startupdigest.com/sample',
    weeklyGrowth: 8,
    createdAt: '2023-02-28',
    language: 'en',
    isFavorite: false
  }
];